trikGui/fileManagerWidget.cpp, trikScriptRunner/src/trikScriptRunner.cpp
1) В режиме "Вся файловая система" путь сверху теперь выглядит  /home/root/trik, а не homeroottrik
2) В режиме "Вся файловая система" просмотр теперь начинается с папки /home/root/trik/scripts
=> fixed CurrentFMPath

trikControl/include/trikControl/displayInterface.h, trikControl/src/display.cpp, trikControl/src/display.h, trikControl/src/guiWorker.cpp, trikControl/src/guiWorker.h
Now explicit 'redraw' call is needed, which will be done in TRIK Studio generators soon
=> Removed tones of extra 'redraw' parameters in drawing methods.

trikControl/model-config-v6.xml, trikControl/system-config-v6.xml, trikControl/trikControl.pro, trikGui/communicationSettingsWidget.cpp, trikKernel/include/trikKernel/version.h, trikNetwork/include/trikNetwork/connection.h, trikNetwork/include/trikNetwork/mailboxInterface.h, trikNetwork/src/connection.cpp, trikNetwork/src/mailbox.cpp, trikNetwork/src/mailbox.h, trikNetwork/src/mailboxServer.cpp, trikNetwork/src/mailboxServer.h, trikScriptRunner/system.js
+ Fixed connecting to mailboxes when third IP address part is "000"
+ Implemented making connect button green when mailbox connected to other
=> Communication improvement

trikScriptRunner/src/scriptExecutionControl.cpp, trikScriptRunner/src/scriptExecutionControl.h
(due to results of 28.12.15 team party)
=> Added support for Luchin time for more decent team time management

trikControl/src/eventDeviceWorker.cpp, trikControl/src/keysWorker.cpp, trikControl/src/rangeSensorWorker.cpp, trikControl/src/vectorSensor.cpp, trikControl/src/vectorSensorWorker.cpp, trikControl/src/vectorSensorWorker.h, trikHal/include/trikHal/hardwareAbstractionInterface.h, trikHal/src/stub/stubHardwareAbstraction.cpp, trikHal/src/stub/stubHardwareAbstraction.h, trikHal/src/trik/trikEventFile.cpp, trikHal/src/trik/trikEventFile.h, trikHal/src/trik/trikHardwareAbstraction.cpp, trikHal/src/trik/trikHardwareAbstraction.h
TODO: Assure that other event files execute in worker thread.
=> Fixed accidental accelerometer segfaulting in JavaScript mode

trikCommunicator/include/trikCommunicator/trikCommunicator.h, trikCommunicator/src/trikCommunicator.cpp, trikNetwork/include/trikNetwork/trikServer.h, trikScriptRunner/include/trikScriptRunner/trikScriptRunner.h, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/trikScriptRunner.cpp, trikTelemetry/src/connection.cpp
Telemetry sends all sensors data as the 1 package
=> Telemetry upd

trikControl/include/trikControl/displayInterface.h, trikControl/src/display.cpp, trikControl/src/display.h, trikControl/src/graphicsWidget.cpp, trikControl/src/graphicsWidget.h, trikControl/src/guiWorker.cpp, trikControl/src/guiWorker.h, trikControl/src/shapes/ellipse.cpp, trikControl/src/shapes/ellipse.h, trikControl/src/shapes/rectangle.cpp, trikControl/src/shapes/rectangle.h
Позволяет рисовать на дисплее заполненные эллипсы и прямоугольники
=> Rect filling

trikKernel/include/trikKernel/configurer.h, trikKernel/src/configurer.cpp
пара небольших правок в классе Configurer
=> Minor fixes

trikControl/include/trikControl/brickInterface.h, trikControl/include/trikControl/gyroSensorInterface.h, trikControl/src/brick.cpp, trikControl/src/brick.h, trikControl/src/eventDeviceWorker.cpp, trikControl/src/gyroSensor.cpp, trikControl/src/gyroSensor.h, trikControl/src/vectorSensorWorker.cpp, trikControl/system-config.xml, trikControl/trikControl.pro, trikKernel/include/trikKernel/timeVal.h, trikKernel/src/timeVal.cpp, trikScriptRunner/src/scriptEngineWorker.cpp
New gyroscope sensor is created. It supports:
1. Converting raw data into angular velocity (without bias) in mdps
2. Counting current orientation of controller by means of gyro data
3. Packed timestamp of current gyro sensor data
Also refactoring of TimeVal class was made:
1. Excess constructors were hidden as private
2. Methods for converting packed data in C++ were added
3. Method for counting time interval from two packed times was added in js
Odr selection of gyro was decreased for increasing gyro accuracy.
=> Gyroscope implemetation

trikScriptRunner/src/scriptEngineWorker.cpp
Moved custom init steps after system.js evaluation.
=> Small custom init steps fixup

trikControl/include/trikControl/markerInterface.h, trikScriptRunner/src/scriptEngineWorker.cpp
FIXED: access to marker from js
Signed-off-by: greg <lahmatbiy@gmail.com>
=> REMOVED: Q_INVOKABLE from markerInterface.h

trikGui/communicationSettingsWidget.cpp, trikGui/trikGuiApplication.cpp, trikGui/wiFiClientWidget.cpp, trikNetwork/include/trikNetwork/connection.h, trikNetwork/include/trikNetwork/mailboxInterface.h, trikNetwork/src/mailbox.cpp, trikNetwork/src/mailbox.h, trikNetwork/src/mailboxServer.cpp, trikNetwork/src/mailboxServer.h, trikNetwork/src/trikServer.cpp, trikWiFi/src/trikWiFiWorker.cpp
Signed-off-by: greg <lahmatbiy@gmail.com>
=> mailbox work and robot connections were improved

trikControl/include/trikControl/brickInterface.h, trikControl/include/trikControl/cameraDeviceInterface.h, trikControl/src/brick.cpp, trikControl/src/brick.h, trikControl/src/cameraDevice.cpp, trikControl/src/cameraDevice.h, trikControl/src/cameraImplementationInterface.cpp, trikControl/src/cameraImplementationInterface.h, trikControl/src/imitationCameraImplementation.cpp, trikControl/src/imitationCameraImplementation.h, trikControl/src/qtCameraImplementation.cpp, trikControl/src/qtCameraImplementation.h, trikControl/src/v4l2CameraImplementation.cpp, trikControl/src/v4l2CameraImplementation.h, trikControl/trikControl.pro, trikGui/trikGuiApplication.cpp, trikHal/src/trik/trikHardwareAbstraction.cpp, trikHal/src/trik/trikV4l2VideoDevice.cpp, trikHal/src/trik/trikV4l2VideoDevice.h
Add camera imitation.
V4l2: choose existing pixel format and after taking shot convert image to RGB888, early converting to RGB888 was in trikHal.
=> Photo implementation

trikControl/src/gyroSensor.cpp, trikControl/src/gyroSensor.h, trikControl/src/lineSensorWorker.cpp, trikControl/src/lineSensorWorker.h, trikControl/src/rangeSensorWorker.cpp, trikControl/src/rangeSensorWorker.h
=> Fixes for frequent lineSensor readings

docker/Dockerfile
Fix for https://github.com/trikset/trik-studio/issues/60
=> Docker: migrate from trusty to xenial

trikControl/src/vectorSensorWorker.cpp, trikControl/src/vectorSensorWorker.h
=> read-write lock for vectorSensor

docker/Dockerfile, docker/install_qt.sh, docker/qt_scriptinstall.qs
Close #283 as obsolete
This PR has lighter docker image.
=> Use Qt5.12 for GNU/Linux build

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/startWidget.cpp
Файлы
Тестирование
Сеть
- Точка доступа
- Клиент
Взаимодействие
Язык
Еще...
- Программирование
- Настройки системы
- Версия и обновление
=> Menu levels redesign

trikControl/src/graphicsWidget.cpp, trikControl/src/graphicsWidget.h
Fix #291 
Now, new shapes are going to redraw old one (like painting over). 
Labels memory their own color and display it like they have to.
=> Shapes and labels knows their own color

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/informationWidget.cpp, trikGui/informationWidget.h, trikKernel/stubHostname, trikKernel/trikKernel.pro
=> Update Version menu

trikControl/src/gamepad.cpp, trikControl/src/gamepad.h
=> Skip keepalive message

trikControl/src/gamepad.cpp, trikControl/src/gamepad.h, trikGui/gamepadIndicator.cpp, trikGui/gamepadIndicator.h
=> Keepalive support

trikControl/include/trikControl/gamepadInterface.h, trikControl/src/gamepad.cpp, trikControl/src/gamepad.h
Signal is now `disconnected`
Slot is `disconnect`
=> Rename gamepad signal, introduce corresponding slot

trikControl/system-config.xml
=> Do not re-init MEMS sensors to default

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/fileManagerWidget.cpp, trikGui/fileManagerWidget.h, trikGui/fileSystemFilter.cpp, trikGui/fileSystemFilter.h, trikGui/trikGui.pro
=> Add "Delete all" item to Files

.travis.yml, tests/testUtils/src/wait.cpp, translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikControl/include/trikControl/displayInterface.h, trikControl/src/guiWorker.h, trikGui/abstractIndicator.h, trikGui/controller.cpp, trikGui/motorLever.cpp, trikGui/sensorIndicator.cpp, trikGui/sensorIndicator.h, trikGui/sensorLever.cpp, trikGui/sensorLever.h, trikHal/src/trik/usbMsp/usbMSP430Interface.cpp
=> Fix lost slot connection

tests/trikCameraPhotoTests/trikCameraPhotoImitationTest.cpp, trikControl/include/trikControl/cameraDeviceInterface.h, trikControl/src/cameraDeviceInterface.cpp, trikControl/src/cameraImplementationInterface.h, trikControl/src/imitationCameraImplementation.cpp, trikControl/src/qtCameraImplementation.cpp, trikControl/trikControl.pro
Also compatibility with Qt 5.13
=> Remove duplicate of helper function

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/fileManagerWidget.cpp, trikGui/fileManagerWidget.h, trikGui/resources/stylesheet.qss
=> Faster message box

trikGui/wiFiClientWidget.cpp, trikGui/wiFiModeWidget.cpp
The problem is similar to https://stackoverflow.com/questions/51438242/qiconaddfile-execute-too-slowly-when-qt-application-startup
Fix #339
=> Use QIcon loading through QPixmap for faster icon loadings

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/languageSelectionWidget.cpp
=> Add two buttons for language change dialog

trikControl/src/audioSynthDevice.cpp, trikControl/src/audioSynthDevice.h, trikControl/src/tonePlayer.cpp, trikControl/src/tonePlayer.h, trikControl/trikControl.pro
=> PLayTone bug fix && small codestyle fixes

trikControl/src/gyroSensor.cpp, trikHal/src/trik/trikV4l2VideoDevice.cpp
Ещё не тестировал, но предполагаю, что этот код должен быть значительно быстрее, поскольку убраны даблы и даже удалось в обработке картинки обойтись без флоатов вообще.
=> Use faster math in video processing and gyro

scripts/runtests.sh
ASan hangs when leaks detection is on. To be fixed later.
=> TravisCI: disable leaks detection in ASan, because in hangs

README.md, tests/trikPyRunnerTests/trikPyRunnerTest.cpp, trikScriptRunner/include/trikScriptRunner/trikPythonRunner.h, trikScriptRunner/src/pythonEngineWorker.cpp, trikScriptRunner/src/pythonEngineWorker.h, trikScriptRunner/src/trikPythonRunner.cpp, trikScriptRunner/src/trikScriptRunner.cpp
startedScript/completed revised. Improved tests
=> Improved PythonRunner threads and events handling

global.pri, resources/lsan.supp, scripts/runtests.sh
=> Link sanitizers statically

tests/trikPyRunnerTests/trikPyRunnerTest.cpp, tests/trikPyRunnerTests/trikPyRunnerTest.h, trikScriptRunner/src/pythonEngineWorker.cpp
1. Fix missing error message
2. Add test for print() (stdout handling)
=> Python: add test for print(), fix missing error message

docker/Dockerfile
More warnings, fewer problems.
=> Docker: switch builds to g++-8 by default

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/wiFiClientWidget.cpp
=> Clean up after previous PR

trikControl/include/trikControl/fifoInterface.h, trikControl/src/fifo.cpp, trikControl/src/fifo.h, trikControl/src/gamepad.cpp, trikHal/include/trikHal/eventFileInterface.h, trikHal/include/trikHal/fifoInterface.h, trikHal/src/trik/trikFifo.cpp, trikHal/src/trik/trikFifo.h, trikScriptRunner/src/scriptExecutionControl.cpp, trikScriptRunner/src/scriptExecutionControl.h
Added new methods for work with bytes and old functions were renamed (onNewData -> onNewLine and etc.) for better code usability.
=> Work with FIFO

tests/trikPyRunnerTests/trikPyRunnerTest.cpp, trikScriptRunner/src/pythonEngineWorker.cpp, trikScriptRunner/src/pythonEngineWorker.h, trikScriptRunner/system.py
=> Add scriptExecutionControl to PythonEngine

deploy.sh, tests/trikJsRunnerTests/trikJsRunnerTest.cpp, tests/trikJsRunnerTests/trikJsRunnerTest.h, tests/trikPyRunnerTests/trikPyRunnerTest.cpp, translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikCommunicator/src/trikCommunicator.cpp, trikGui/controller.cpp, trikRun/trikRunMain.cpp, trikScriptRunner/include/trikScriptRunner/trikJavaScriptRunner.h, trikScriptRunner/include/trikScriptRunner/trikPythonRunner.h, trikScriptRunner/include/trikScriptRunner/trikScriptRunner.h, trikScriptRunner/include/trikScriptRunner/trikScriptRunnerInterface.h, trikScriptRunner/src/pythonEngineWorker.cpp, trikScriptRunner/src/pythonEngineWorker.h, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptExecutionControl.h, trikScriptRunner/src/trikJavaScriptRunner.cpp, trikScriptRunner/src/trikPythonRunner.cpp, trikScriptRunner/src/trikScriptRunner.cpp, trikScriptRunner/system.py
=> [WIP] Print to console from send message signal

scripts/install.sh, scripts/runtests.sh, scripts/script.sh, tests/trikPyRunnerTests/trikPyRunnerTest.cpp
=> macOS related fixes

translations/fr/trikGui_fr.ts, translations/fr/trikScriptRunner_fr.ts, translations/ru/trikGui_ru.ts, translations/ru/trikScriptRunner_ru.ts, trikGui/runningWidget.cpp, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptEngineWorker.h, trikScriptRunner/src/scriptThread.cpp, trikScriptRunner/system.js
Fix #473 + add backtrace, that contains name of file.
=> Include support in ScriptEngine

tests/trikJsRunnerTests/trikJsRunnerTest.cpp, tests/trikPyRunnerTests/trikPyRunnerTest.cpp, translations/fr/trikScriptRunner_fr.ts, translations/ru/trikScriptRunner_ru.ts, trikControl/src/display.cpp, trikScriptRunner/src/pythonEngineWorker.cpp, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptExecutionControl.cpp, trikScriptRunner/src/scriptExecutionControl.h, trikScriptRunner/src/trikJavaScriptRunner.cpp, trikScriptRunner/src/trikPythonRunner.cpp, trikScriptRunner/system.js, trikScriptRunner/system.py
=> getPhoto for Python 

docker/qt_scriptinstall.qs, scripts/install_qt_mac.sh
Support ObligationsPage from QTIFw 3.2
Add IFW 3.2 as default
Use link to latest (3.2) online installer for macOS
Minor fixes
=> Update Qt silent install script

trikControl/src/abstractVirtualSensorWorker.cpp
=> Small fix on new signals syntax

trikScriptRunner/src/pythonEngineWorker.cpp
=> Python: Fix duplicates in sys.path

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/cameraWidget.cpp, trikKernel/include/trikKernel/paths.h, trikKernel/src/stub/paths.cpp, trikKernel/src/trik/paths.cpp
=> Saving images

trikHal/src/trik/trikV4l2VideoDevice.cpp
=> Fix for color schemes converting

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/communicationSettingsWidget.cpp, trikGui/numberSelectionWidget.cpp, trikGui/numberSelectionWidget.h
=> Redraw in numberSelectionWidget

trikControl/src/guiWorker.cpp, trikScriptRunner/src/scriptExecutionControl.cpp
We did it for [this issue](https://github.com/trikset/trik-studio/issues/722)
=> Register QVector in ScriptExecutionControl

trikScriptRunner/src/pythonEngineWorker.cpp
=> No twice system.py

tests/trikJsRunnerTests/trikJsRunnerTest.cpp, translations/fr/trikScriptRunner_fr.ts, translations/ru/trikScriptRunner_ru.ts, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/trikPythonRunner.cpp
=> While True fix 

global.pri, runVera++.sh, tests/trikJsRunnerTests/data/async-system-test.js, tests/trikJsRunnerTests/trikJsRunnerTest.cpp, translations/fr/trikGui_fr.ts, translations/fr/trikScriptRunner_fr.ts, translations/ru/trikGui_ru.ts, translations/ru/trikScriptRunner_ru.ts, trikControl/src/gyroSensor.cpp, trikControl/src/gyroSensor.h, trikGui/accelerometerWidget.cpp, trikGui/gyroscopeIndicator.cpp, trikGui/startWidget.cpp, trikKernel/include/trikKernel/exceptions/failedToOpenFileException.h, trikKernel/src/stub/paths.cpp, trikNetwork/include/trikNetwork/trikServer.h, trikNetwork/src/mailbox.cpp, trikNetwork/src/mailboxServer.cpp, trikNetwork/src/mailboxServer.h, trikNetwork/src/trikServer.cpp, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptEngineWorker.h, trikScriptRunner/src/trikJavaScriptRunner.cpp, trikScriptRunner/src/trikPythonRunner.cpp, vera++/scripts/rules/NoOldSIGNALnSLOT.tcl
Fix crash when accel or gyro is not available
Fix strange menu item behavior caused by editablity
Q_ASSERT in release
Playing with threads...
=> Few different fixes

translations/fr/trikScriptRunner_fr.ts, translations/ru/trikScriptRunner_ru.ts, trikScriptRunner/include/trikScriptRunner/trikJavaScriptRunner.h, trikScriptRunner/include/trikScriptRunner/trikPythonRunner.h, trikScriptRunner/include/trikScriptRunner/trikScriptRunner.h, trikScriptRunner/include/trikScriptRunner/trikScriptRunnerInterface.h, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptEngineWorker.h, trikScriptRunner/src/trikJavaScriptRunner.cpp, trikScriptRunner/src/trikPythonRunner.cpp, trikScriptRunner/src/trikScriptRunner.cpp
=> Working dir for include

trikScriptRunner/system.py
=> Inititalize gamepad

docker/Dockerfile
=> Update Docker to use Qt 5.12 from PPA

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/networkWidget.cpp, trikGui/networkWidget.h, trikNetwork/src/mailbox.cpp
=> Add hull number to main screen

trikControl/include/trikControl/brickInterface.cpp, trikControl/include/trikControl/brickInterface.h, trikControl/src/brick.cpp, trikControl/trikControl.pro
Fix #517 
Register metatype in brickInterface instance
=> Register metatype in brickInterface instance

trikNetwork/src/mailbox.cpp, trikNetwork/src/trikServer.cpp
There was dangerous directConnection
=> Mailbox fix method calls

trikNetwork/src/connection.cpp, trikNetwork/src/mailboxServer.cpp
There was a segmentation fault when we were sending data.
=> Fix bug with mailbox

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikControl/src/cameraDevice.cpp, trikGui/abstractIndicator.h, trikGui/cameraWidget.cpp, trikGui/cameraWidget.h, trikGui/sensorsWidget.cpp, trikGui/sensorsWidget.h
Click on return to recreate photo
Fix #521
=> Camera button

trikControl/src/brick.cpp, trikGui/backgroundWidget.cpp, trikGui/trikGuiApplication.cpp
=> Brick beeps after load

trikScriptRunner/include/trikScriptRunner/trikScriptRunner.h, trikScriptRunner/src/pythonEngineWorker.cpp, trikScriptRunner/src/pythonEngineWorker.h, trikScriptRunner/src/trikJavaScriptRunner.cpp, trikScriptRunner/src/trikPythonRunner.cpp, trikScriptRunner/src/trikScriptRunner.cpp
Fix #506 
```Python
import sys
print(sys.path)
```
Output:
`['/usr/lib/python3.6/', '/home/khodand/trik/build-studio-Desktop_Qt_5_12_5_GCC_64bit-Debug/bin/debug', '/home/khodand/.local/share/trik-studio/trik/say']`
=> Fixing import bug

trikGui/accelerometerWidget.cpp, trikGui/accelerometerWidget.h, trikGui/gyroscopeIndicator.cpp, trikGui/gyroscopeIndicator.h, trikGui/sensorsWidget.cpp
Trying to fix this https://github.com/trikset/trik-webpanel/issues/72
=> Checking whether the sensor was enabled.

PythonQt/runme.sh, pythonqt/mjb_rejected_classes.log, pythonqt/mjb_rejected_enums.log, pythonqt/mjb_rejected_functions.log, qslog/QsLogDestFile.cpp, tests/trikJsRunnerTests/trikJsRunnerTest.cpp, translations/fr/trikGui_fr.ts, translations/fr/trikKernel_fr.ts, translations/ru/trikGui_ru.ts, translations/ru/trikKernel_ru.ts, trikControl/src/graphicsWidget.cpp, trikControl/src/graphicsWidget.h, trikControl/src/guiWorker.cpp, trikControl/src/utilities.cpp, trikGui/controller.cpp, trikGui/updateWidget.cpp, trikHal/src/trik/trikV4l2VideoDevice.cpp, trikHal/src/trik/trikV4l2VideoDevice.h, trikKernel/src/applicationInitHelper.cpp, trikNetwork/src/mailboxServer.cpp, trikScriptRunner/PyTrikControl/PyTrikControl0.cpp, trikScriptRunner/PyTrikControl/PyTrikControl0.h, trikScriptRunner/PyTrikControl/PyTrikControl_init.cpp, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptExecutionControl.cpp
playTone instead of beep.wav
fix: uninitialized array is displayed in `show` after getPhoto() fails, fixes #535
Qt 5.14, Qt 5.15 related fixes
=> Small fixes and new Qt support

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/cameraWidget.cpp, trikGui/cameraWidget.h
No creating photo if it is in progress
=> Fixing testing camera lag

trikControl/configs/kernel-3.6/model-config.xml, trikControl/configs/kernel-3.6/system-config.xml
For https://github.com/trikset/trik-webpanel/issues/15 issue
=> Create 100RPM motors

runVera++.sh, scripts/script.sh, trikControl/src/cameraImplementationInterface.h, trikControl/src/imitationCameraImplementation.cpp, trikControl/src/imitationCameraImplementation.h, trikControl/src/qtCameraImplementation.cpp, trikControl/src/v4l2CameraImplementation.cpp, trikHal/include/trikHal/hardwareAbstractionInterface.h, trikHal/src/stub/stubHardwareAbstraction.cpp, trikHal/src/stub/stubHardwareAbstraction.h, trikHal/src/trik/trikHardwareAbstraction.cpp, trikHal/src/trik/trikHardwareAbstraction.h
=> Support QT 5.14.1 and Submodules update

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikGui/startWidget.cpp
=> Init camera in testing menu

appveyor.yml
Use VS2015 (default) image to fix builds
=> Submodules updates

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikControl/include/trikControl/utilities.h, trikControl/src/utilities.cpp, trikControl/trikControl.pro, trikGui/cameraWidget.cpp, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptExecutionControl.cpp
=> getPhoto code in camera testing

trikScriptRunner/system.py
=> Constants and getPhoto

trikScriptRunner/src/pythonEngineWorker.cpp
=> Add mailbox to Python

.travis.yml, docker/Dockerfile, scripts/script.sh
As a first step to Python3.7 from Linux
=> Use PYTHON3_VERSION_MINOR

trikControl/include/trikControl/displayInterface.h, trikControl/src/display.cpp, trikControl/src/display.h, trikControl/src/graphicsWidget.cpp, trikControl/src/graphicsWidget.h, trikControl/src/guiWorker.cpp, trikControl/src/guiWorker.h
Part of the [issue](https://github.com/trikset/trik-studio/issues/985) fix.
=> Font size property in addLabel

trikControl/src/utilities.cpp
=> Support greyscale8 name

qslog/QsLogSharedLibrary.pro, tests/trikJsRunnerTests/trikJsRunnerTest.cpp, trikCommunicator/trikCommunicator.pro, trikControl/trikControl.pro, trikControl/trikControlExport.pri, trikGui/trikGui.pro, trikHal/trikHal.pro, trikKernel/trikKernel.pro, trikNetwork/trikNetwork.pro, trikRun/trikRun.pro, trikRuntime.pro, trikScriptRunner/trikScriptRunner.pro, trikServer/trikServer.pro, trikWiFi/trikWiFi.pro
Because we build it, not the distro's version is used
=> Rename qslog → trikQsLog to avoid confusion

trikHal/src/trik/trikV4l2VideoDevice.cpp
Swap red and blue for OV7670 YUV422p
=> Fix colors for getPhoto

trikScriptRunner/include/trikScriptRunner/trikJavaScriptRunner.h, trikScriptRunner/include/trikScriptRunner/trikPythonRunner.h, trikScriptRunner/include/trikScriptRunner/trikScriptControlInterface.h, trikScriptRunner/include/trikScriptRunner/trikScriptRunner.h, trikScriptRunner/src/pythonEngineWorker.cpp, trikScriptRunner/src/pythonEngineWorker.h, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptEngineWorker.h, trikScriptRunner/src/scriptExecutionControl.cpp, trikScriptRunner/src/scriptExecutionControl.h, trikScriptRunner/src/threading.cpp, trikScriptRunner/src/threading.h, trikScriptRunner/src/trikJavaScriptRunner.cpp, trikScriptRunner/src/trikPythonRunner.cpp, trikScriptRunner/src/trikScriptRunner.cpp, trikScriptRunner/trikScriptRunner.pro
Renamed scriptExecutionControl to trikScriptExecutionControl
Moved to become available in the studio.
=> TrikScriptExecutionControl as trikScriptRunner attribute

tests/testUtils/src/tcpClientSimulator.cpp, tests/trikJsRunnerTests/trikJsRunnerTest.cpp, trikNetwork/include/trikNetwork/connection.h, trikNetwork/src/connection.cpp, trikScriptRunner/include/trikScriptRunner/trikScriptControlInterface.h, trikScriptRunner/include/trikScriptRunner/trikScriptRunnerInterface.h, trikScriptRunner/src/pythonEngineWorker.cpp
Reset script engine state (and cleanup timers  after script execution.
And small refactoring
=> trikNetwork: add TCP_NODELAY to socket

trikNetwork/src/connection.cpp
to handle `connected` signal properly
=> Create timers before connection

trikScriptRunner/src/pythonEngineWorker.cpp
It could be done in system.py in theory (we can create something like `__trik_all_aliases_list__`  and clear all names except these)
=> Eval reset for all names in python interpreter [AUTOZIP]

appveyor.yml, global.pri
=> Fix Appveyor build

trikCommunicator/src/connection.cpp, trikScriptRunner/include/trikScriptRunner/trikPythonRunner.h, trikScriptRunner/include/trikScriptRunner/trikScriptRunner.h, trikScriptRunner/src/pythonEngineWorker.cpp, trikScriptRunner/src/pythonEngineWorker.h, trikScriptRunner/src/trikPythonRunner.cpp, trikScriptRunner/src/trikScriptRunner.cpp
Needs for https://github.com/trikset/trik-studio/pull/1132
=> QWaitCondition and BlockingQueue on beep

trikControl/src/fifo.cpp, trikControl/src/fifo.h, trikControl/src/fifoworker.cpp, trikControl/src/fifoworker.h, trikControl/trikControl.pro
=> New worker class for Fifo

trikGui/batteryIndicator.cpp, trikGui/batteryIndicator.h
=> Several high beeps in 10 seconds

trikControl/src/cameraDevice.cpp, trikControl/src/colorSensor.cpp, trikControl/src/eventDevice.cpp, trikControl/src/fifo.cpp, trikControl/src/gyroSensor.cpp, trikControl/src/keys.cpp, trikControl/src/lineSensor.cpp, trikControl/src/objectSensor.cpp, trikControl/src/rangeSensor.cpp, trikControl/src/soundSensor.cpp, trikControl/src/vectorSensor.cpp, trikNetwork/src/mailbox.cpp, trikNetwork/src/trikServer.cpp, trikScriptRunner/src/threading.cpp, trikScriptRunner/src/trikJavaScriptRunner.cpp, trikScriptRunner/src/trikPythonRunner.cpp, trikWiFi/src/trikWiFi.cpp
=> Name every thread that start as worker's className

trikControl/src/keys.cpp, trikControl/src/keys.h, trikControl/src/keysWorker.cpp, trikControl/src/keysWorker.h
=> Wait for buttons with eventLoop and stopWaiting on reset

azure-pipelines.yml, scripts/azure/after_script.sh, scripts/azure/install_Darwin.sh, scripts/azure/install_Linux.sh, scripts/azure/runVera++.sh, scripts/azure/runtests.sh, scripts/azure/script.sh, trikControl/src/datafilter.h, trikControl/src/keys.h, trikKernel/include/trikKernel/exceptions/trikRuntimeException.h, trikNetwork/include/trikNetwork/connection.h
=> Set up CI with Azure Pipelines

trikScriptRunner/TRIK.py, trikScriptRunner/src/pythonEngineWorker.cpp, trikScriptRunner/src/pythonEngineWorker.h, trikScriptRunner/trikScriptRunner.pro
https://github.com/trikset/trik-studio/issues/1165
Fixes #650 
Now, to use TRIK builtins in custom modules:
```python
import TRIK
from TRIK import *
```
=> Add trik builtins as separate module

translations/fr/trikGui_fr.ts, translations/ru/trikGui_ru.ts, trikControl/configs/kernel-3.6/system-config.xml, trikControl/include/trikControl/pwmCaptureInterface.h, trikControl/src/configurerHelper.cpp, trikControl/src/configurerHelper.h, trikControl/src/pwmCapture.cpp, trikControl/src/pwmCapture.h, trikGui/pwmCaptureIndicator.cpp, trikGui/pwmCaptureIndicator.h, trikGui/sensorsWidget.cpp, trikGui/sensorsWidget.h, trikGui/startWidget.cpp, trikGui/trikGui.pro, trikScriptRunner/include/trikScriptRunner/trikScriptRunnerInterface.h
Corresponding model PR is https://github.com/trikset/trik-models/pull/38.
TODOs are in the #732
=> Add basic PWM capture support

tests/test-model-config.xml, tests/test-system-config.xml, trikControl/configs/kernel-4.14/model-config.xml, trikControl/configs/kernel-4.14/system-config.xml, trikControl/src/brick.cpp, trikControl/src/gyroSensor.cpp, trikControl/src/gyroSensor.h, trikControl/src/vectorSensor.cpp, trikControl/src/vectorSensor.h, trikHal/include/trikHal/IIOFileInterface.h, trikHal/include/trikHal/hardwareAbstractionInterface.h, trikHal/src/stub/stubHardwareAbstraction.cpp, trikHal/src/stub/stubHardwareAbstraction.h, trikHal/src/stub/stubIIOFile.cpp, trikHal/src/stub/stubIIOFile.h, trikHal/src/trik/trikHardwareAbstraction.cpp, trikHal/src/trik/trikHardwareAbstraction.h, trikHal/src/trik/trikIIOFile.cpp, trikHal/src/trik/trikIIOFile.h, trikKernel/include/trikKernel/configurer.h, trikKernel/src/configurer.cpp
Added a scan_type check to convert accelerometer and gyroscope data.
For the future, the accelerometer and gyroscope now have ports.
=> Fix conversion of accelerometer and gyroscope data.

.github/workflows/main.yml, tests/mainTest.cpp, tests/testUtils/src/wait.cpp, tests/trikJsRunnerTests/data/file-test.js, tests/trikJsRunnerTests/trikJsRunnerTest.cpp, tests/trikJsRunnerTests/trikJsRunnerTests.pro, tests/trikJsRunnerTests/trikJsRunnerTests.qrc, tests/trikPyRunnerTests/trikPyRunnerTest.cpp, trikKernel/include/trikKernel/fileUtils.h, trikKernel/include/trikKernel/loggingHelper.h, trikKernel/src/applicationInitHelper.cpp, trikKernel/src/loggingHelper.cpp, trikScriptRunner/src/scriptThread.cpp, trikScriptRunner/src/threading.cpp, trikScriptRunner/src/threading.h
Add PYTHONDEVMODE=1
Add Qt5.15 Windows CI
Improve logging
=> Improve tests

tests/common.pri, tests/mainTest.cpp, tests/testUtils/include/testUtils/eventFilter.h, tests/testUtils/src/eventFilter.cpp, tests/testUtils/testUtils.pro, tests/trikPyRunnerTests/trikPyRunnerTest.cpp, trikScriptRunner/src/pythonEngineWorker.cpp, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptExecutionControl.cpp, trikScriptRunner/src/trikJavaScriptRunner.cpp, trikScriptRunner/src/trikPythonRunner.cpp, trikScriptRunner/src/trikScriptRunner.cpp
New `script.wait` tries hard to be as precise as desired without meaningful deviation on different platform (TRIK, macOS, Windows, GNU/Linux desktops and servers)
Also some improvements for responsiveness
=> Improved script.wait

trikScriptRunner/src/pythonEngineWorker.cpp
=> Fix undefined Py<...> symbols for imported modules

trikControl/include/trikControl/brickInterface.h, trikControl/src/brick.cpp, trikNetwork/include/trikNetwork/mailboxInterface.h, trikNetwork/src/mailbox.cpp, trikNetwork/src/mailbox.h, trikScriptRunner/src/scriptEngineWorker.cpp, trikScriptRunner/src/scriptEngineWorker.h, trikScriptRunner/src/scriptExecutionControl.cpp
- **Log incorrect call to JS::abort**
- **Fix call chain mess with threads**
=> Fix crashes with threading issues
