trikset/trikRuntime

trikControl/src/linux/sensor3dWorker.cpp
trikControl/src/sensor3dWorker.h

-10% sys CPU & -10% usr CPU in 'top'

Lock-free read for gyro & accel.

---

trikGui/motorsWidget.cpp
trikGui/motorsWidget.h

Not ideal, because there is a widget that gets focus between M4/M1 or S6/S1. This was also present on Qt Embedded and needs just a bit of further investigation

Fixed selection of motors inside motorsWidget (X11)

---

trikControl/src/gyroSensor.h

Error in roll formula is fixed in accordance with https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles#Quaternion_to_Euler_Angles_Conversion

Roll formula

---

appveyor.yml

To avoid `Error sending Slack notification: Error sending Slack message: no_service`
We use Appveyor web configuration

Remove Slack integration from appveyor.yml

---

trikControl/include/trikControl/displayInterface.h
trikControl/src/display.cpp
trikControl/src/display.h
trikControl/src/guiWorker.cpp
trikControl/src/guiWorker.h

Fix #316
Now it can be used like this:
```
//rgb32
var photo = getPhoto();
brick.display().show(photo, 160, 120, "rgb32");
script.wait(5000);
//rgb888
pic = []
photo = getPhoto();
l = photo.length;
for (i = 0; i < l; i++) {
var p = photo[i];
pic.push((p&0xff0000)>>16);
pic.push((p&0xff00)>>8);
pic.push((p&0xff));
}
brick.display().show(pic, 160, 120, "rgb888");
script.wait(5000);                            
//grayscale8                                   
pic = []                                      
photo = getPhoto();
l = photo.length;                             
for (i = 0; i < l; i++) {                     
var p = photo[i];                     
pic.push(((p&0xff0000)>>18) + ((p&0xff00)>>10) + ((p&0xff)>>2));                
} …
```

Add show method for pixel array drawing

---

trikControl/include/trikControl/gamepadInterface.h
trikControl/src/fifo.cpp
trikControl/src/fifo.h
trikControl/src/gamepad.cpp
trikControl/src/gamepad.h
trikScriptRunner/src/pythonEngineWorker.cpp

Useful for extensibility, when gamepad is used as a simple TCP interface
accessible from script.
Designed to work only in event-driven mode

Dispatch custom message from gamepad port

---

trikScriptRunner/src/pythonEngineWorker.cpp
trikScriptRunner/system.py

Object "script" is python class now because if we use cpp class we can not modify it in python scripts.

Script is python class

---

trikScriptRunner/src/pythonEngineWorker.cpp
trikScriptRunner/src/trikPythonRunner.cpp

Extension for #496 bug. Because when Python script stops with `while True`, trikGui goes to deadlock.

Fix deadlocking after abort signal

---

trikControl/src/guiWorker.cpp
trikControl/src/utilities.cpp

Если мы создаем массив для вывода show  в javascript, а не перезаписываем буфер, который нам вернул getPhoto, то на экран выводится всякий мусор.

Fix show image 

---

translations/fr/trikScriptRunner_fr.ts
translations/ru/trikScriptRunner_ru.ts
trikScriptRunner/src/scriptEngineWorker.cpp
trikScriptRunner/src/scriptEngineWorker.h

Keep absolute path in `include`, but resolve relative path.

Fix for old JS scripts with absolute path in `include`

---

trikControl/src/eventDevice.cpp
trikControl/src/eventDeviceWorker.cpp
trikControl/src/eventDeviceWorker.h
trikControl/src/keys.cpp
trikControl/src/keysWorker.cpp
trikControl/src/keysWorker.h
trikControl/src/rangeSensorWorker.cpp
trikControl/src/vectorSensorWorker.cpp
trikControl/src/vectorSensorWorker.h

The EventFile was created before moveToThread, so to avoid this, we
eventFile.reset() in the init section that starts after the new thread
is started.

Fix trikGui crash and non-working keys

---

trikScriptRunner/include/trikScriptRunner/trikAbstractTimer.h
trikScriptRunner/include/trikScriptRunner/trikRealTimer.h
trikScriptRunner/include/trikScriptRunner/trikScriptControlInterface.h
trikScriptRunner/include/trikScriptRunner/trikScriptRunnerDeclSpec.h
trikScriptRunner/src/scriptExecutionControl.cpp
trikScriptRunner/src/scriptExecutionControl.h
trikScriptRunner/src/trikAbstractTimer.cpp
trikScriptRunner/src/trikRealTimer.cpp
trikScriptRunner/src/trikScriptControlInterface.cpp
trikScriptRunner/trikScriptRunner.pro

Moved the `AbstractTimer` and its heir `RealTimer` from the studio to the runtime.

TrikAbstractTimer class in scriptControl

---

translations/fr/trikScriptRunner_fr.ts
translations/ru/trikScriptRunner_ru.ts
trikScriptRunner/include/trikScriptRunner/trikScriptControlInterface.h
trikScriptRunner/src/pythonEngineWorker.cpp
trikScriptRunner/src/scriptEngineWorker.cpp
trikScriptRunner/src/scriptExecutionControl.cpp
trikScriptRunner/src/scriptExecutionControl.h

No global `timeIterval` function for js now. Only `script.timeInterval`.
Fixes #663

Move timeInterval to common scriptExecutionControl

---

trikScriptRunner/include/trikScriptRunner/trikJavaScriptRunner.h
trikScriptRunner/include/trikScriptRunner/trikPythonRunner.h
trikScriptRunner/src/trikJavaScriptRunner.cpp
trikScriptRunner/src/trikPythonRunner.cpp

`abort()` can be called from another thread when the field `mScriptEngineWorker` have been deleted by `deleteLater`
this is (probably?) a design issue, but QPointer helps

Fix crash after stop.

---

trikNetwork/src/connection.cpp
trikNetwork/src/mailbox.cpp
trikNetwork/src/mailbox.h
trikNetwork/src/mailboxServer.cpp
trikNetwork/src/mailboxServer.h
trikNetwork/src/trikServer.cpp

Because of the subscription in the method `connectTo` at the start of each new socket - each connection was reconnected again.
There was also a problem because we didn't save the new clientPort when we called `prepareConnection`

Fix connection between several robots

---

trikControl/src/lidarWorker.cpp
trikControl/src/lidarWorker.h

* drop expensive abstractions - TrikFifo, Fifo, FifoWorker etc
* setup serial port speed
This changes are not portable, fix it ASAP
Signed-off-by: Kirill K. Smirnov <kirill.k.smirnov@gmail.com>

Speed up lidar data processing

---

.github/workflows/trik-toolchain.yml
scripts/azure/install_Linux.sh
trikHal/trikHal.pro
trikKernel/trikKernel.pro
trikScriptRunner/src/pythonEngineWorker.cpp

At some point after the TRIK 20220613 firmware release, the build using the TRIK toolchain broke. 
Fix required:
* wrapping some code for newer Python version with preprocessor directives;
* downgrading Google Test to v1.10.0. Despite v1.12.1 being the last version to support C++11, GCC 4.9 in the TRIK toolchain has incomplete support of C++11. 
To prevent this issue the addition of CI workflow with the TRIK toolchain is required. This PR adds workflow with two build configurations:
* `[TRIK brick]` compiles runtime as if it was compiled for TRIK controller;
* `[QEMU + NoPython]` compiles runtime for ARM without TRIK-specific hardware info and then runs test suite using QEMU. Currently, the Python engine is broken for some reason and thus must be disabled to pass the tests.

Add CI with TRIK toolchain

---

.github/workflows/trik-toolchain.yml

[#725](https://github.com/trikset/trikRuntime/pull/725) incorrectly compares string with boolean value, causing CI to always fail with non-existing cache

Fix comparison with string in TRIK toolchain CI

---

trikNetwork/include/trikNetwork/mailboxInterface.h
trikNetwork/src/mailbox.cpp
trikNetwork/src/mailbox.h
trikNetwork/src/mailboxServer.cpp
trikNetwork/src/mailboxServer.h

A minimal `PR` (without cute config files, refactoring, and so on) for implementing the `joinNetwork` block (sets the board number and connects to the robot via IP and port).

Add support for joinNetwork block

---

tests/kernel-4.14/test-system-config.xml
trikControl/configs/kernel-4.14/system-config.xml
trikControl/src/rangeSensor.cpp

1) Change the path to the keys device file for linux kernel 4.14
2) Do not need to reset the sensor state if it has become a fail (it has become a fault for a reason). One example of a real error: due to the incorrect path to the device file, the sensor state became fail, after that, during initialization, this state was reset and when trying to read data from this sensor, the program terminated with SEGFAULT.

Remove reset the range sensor state, change the path to the keys device file

---

trikControl/src/guiWorker.cpp

For a DisplayWidget that is called from user scripts, you do not need to set the window size, since its size depends on the parent widget and the layout in which we put it. Moreover, for Qt 5.15, because of this line, the widget DisplayWidget is not displayed at all, since it has already been installed in layout.

Remove the window state setting for DisplayWidget

---

trikNetwork/src/mailboxServer.cpp

1. The hostname/ip check takes place in `QHostInfo::fromName(ip)` in some lines below

Remove unnecessary ip verification

---

tests/kernel-3.6/test-system-config.xml
tests/kernel-4.14/test-system-config.xml
trikControl/configs/kernel-3.6/system-config.xml
trikControl/configs/kernel-4.14/system-config.xml
trikControl/src/pwmCapture.cpp
trikControl/src/servoMotor.cpp
trikKernel/include/trikKernel/configurer.h
trikKernel/src/configurer.cpp

For ports S1, S2, S3, if they are in servo mode, it is necessary to write to captureFile 0.
For capture mode, you need to write to captureFile 1.
captureFile is not needed for ports S4, S5, S6.

Add support for PWM servo mode and PWM capture mode.

---

trikScriptRunner/src/trikPythonRunner.cpp

When the destructor of `trikPythonRunner` is called, `mWorkerThread->quit()` is invoked. The `finished` signal of `mWorkerThread` is connected to `pythonEngineWorker::deleteLater`. However, when attempting to free resources immediately after script execution (in `PythonEngineWorker::doRun()`), calls to `QCoreApplication::processEvents` reset the `interrupt` flag set by `mWorkerThread->quit()`. As a result, `QEventLoop::exec` [calls](https://github.com/qt/qtbase/blob/7a7804d4b454021d68d1d5138d134ef62abfcdb3/src/corelib/kernel/qeventloop.cpp#L195) bloking [`MsgWaitForMultipleObjectsEx`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-msgwaitformultipleobjectsex)  (via `QEventDispatcherWin32::processEvents`)  with the …

Fix the deadlock in trikPythonRunner

---

trikScriptRunner/src/pythonEngineWorker.cpp

Although the main interpreter thread executes PythonEngineWorker under the GIL after PyEval_InitThreads, upon interrupting the script with SIGINT, the current thread ends up in a state without holding the GIL.
1. `Py_AddPendingCall` does not require `GIL` and `PythonQtGILScope _` before it, and causes a lock when trying to stop the script because the `GIL`  is held by instructions from the user script.
2. More correct recovery after handling `PyErr_SetInterrupt` while holding the `GIL`
Update:
Use `_PyEval_AddPendingCall` in a specific mode to ensure that `COMPUTE_EVAL_BREAKER` 
`&ceval2->pending.calls_to_do` is equal to 1. Perhaps a more natural solution is to use `PythonQtGilScope`, as `COMPUTE_EVAL_BREAKER` first looks at `&ceval2->gil_drop_request` and sets `eval_breaker` to 1, which …

Fix deadlock or crash on Python script interruption
